
#include "s21_math.h"

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

double my_inf = 1.0 / 0.0;
double my_min_inf = -1.0 / 0.0;
double my_nan = 0.0 / 0.0;
double min_nan = -0.0 / 0.0;
double zero = 0;
double min_zero = -0;
double small_num = 1;
double min_small_num = -1;
double num = 100;
double min_num = -100;
double big_num = 666666;
double min_big_num = -666666;
double zf = 0.5;
double mzf = -0.5;
double tf = 2.5;
double mtf = -2.5;
double big_float = 1234.456789;
double min_big_float = -1234.456789;
double small = 0.0000001;
double min_small = -0.0000001;
double long_double = 0.3425443513423432432432;
double min_long_double = -0.3425443513423432432432;
int flag = 0;
double x;
double y;
char str1[100] = {'\0'};
char str2[100] = {'\0'};

START_TEST(abs_test) {
  int my_inf = 1.0 / 0.0;
  int my_min_inf = -1.0 / 0.0;
  int my_nan = 0.0 / 0.0;
  int min_nan = -0.0 / 0.0;
  int zero = 0;
  int min_zero = -0;
  int small_num = 1;
  int min_small_num = -1;
  int num = 100;
  int min_num = -100;
  int big_num = 666666;
  int min_big_num = -666666;
  ck_assert_int_eq(s21_abs(my_inf), abs(my_inf));
  ck_assert_int_eq(s21_abs(my_min_inf), abs(my_min_inf));
  ck_assert_int_eq(s21_abs(my_nan), abs(my_nan));
  ck_assert_int_eq(s21_abs(min_nan), abs(min_nan));
  ck_assert_int_eq(s21_abs(zero), abs(zero));
  ck_assert_int_eq(s21_abs(min_zero), abs(min_zero));
  ck_assert_int_eq(s21_abs(big_num), abs(big_num));
  ck_assert_int_eq(s21_abs(min_big_num), abs(min_big_num));
  ck_assert_int_eq(s21_abs(num), abs(num));
  ck_assert_int_eq(s21_abs(min_num), abs(min_num));
  ck_assert_int_eq(s21_abs(small_num), abs(small_num));
  ck_assert_int_eq(s21_abs(min_small_num), abs(min_small_num));
}
END_TEST

START_TEST(fabs_test) {
  if (s21_fabs(my_inf) == fabs(my_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(my_min_inf) == fabs(my_min_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  ck_assert_int_eq(s21_fabs(my_nan), fabs(my_nan));
  ck_assert_int_eq(s21_fabs(min_nan), fabs(min_nan));
  ck_assert_int_eq(s21_fabs(zero), fabs(zero));
  ck_assert_int_eq(s21_fabs(min_zero), fabs(min_zero));
  if (s21_fabs(small_num) == fabs(small_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(min_small_num) == fabs(min_small_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(num) == fabs(num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(min_num) == fabs(min_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(big_num) == fabs(big_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(min_big_num) == fabs(min_big_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(zf) == fabs(zf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(mzf) == fabs(mzf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(tf) == fabs(tf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(mtf) == fabs(mtf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(big_float) == fabs(big_float)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(min_big_float) == fabs(min_big_float)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(small) == fabs(small)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(min_small) == fabs(min_small)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(long_double) == fabs(long_double)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_fabs(min_long_double) == fabs(min_long_double)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
}
END_TEST

START_TEST(floor_test) {
  if (s21_floor(my_inf) == floor(my_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(my_min_inf) == floor(my_min_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  ck_assert_int_eq(s21_floor(my_nan), floor(my_nan));
  ck_assert_int_eq(s21_floor(min_nan), floor(min_nan));
  ck_assert_int_eq(s21_floor(zero), floor(zero));
  ck_assert_int_eq(s21_floor(min_zero), floor(min_zero));
  if (s21_floor(small_num) == floor(small_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(min_small_num) == floor(min_small_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(num) == floor(num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(min_num) == floor(min_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(big_num) == floor(big_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(min_big_num) == floor(min_big_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(zf) == floor(zf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(mzf) == floor(mzf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(tf) == floor(tf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(mtf) == floor(mtf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(big_float) == floor(big_float)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(min_big_float) == floor(min_big_float)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(small) == floor(small)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(min_small) == floor(min_small)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(long_double) == floor(long_double)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_floor(min_long_double) == floor(min_long_double)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
}
END_TEST

START_TEST(ceil_test) {
  if (s21_ceil(my_inf) == ceil(my_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(my_min_inf) == ceil(my_min_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  ck_assert_int_eq(s21_ceil(my_nan), ceil(my_nan));
  ck_assert_int_eq(s21_ceil(min_nan), ceil(min_nan));
  ck_assert_int_eq(s21_ceil(zero), ceil(zero));
  ck_assert_int_eq(s21_ceil(min_zero), ceil(min_zero));
  if (s21_ceil(small_num) == ceil(small_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(min_small_num) == ceil(min_small_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(num) == ceil(num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(min_num) == ceil(min_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(big_num) == ceil(big_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(min_big_num) == ceil(min_big_num)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(zf) == ceil(zf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(mzf) == ceil(mzf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(tf) == ceil(tf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(mtf) == ceil(mtf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(big_float) == ceil(big_float)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(min_big_float) == ceil(min_big_float)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(small) == ceil(small)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(min_small) == ceil(min_small)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(long_double) == ceil(long_double)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_ceil(min_long_double) == ceil(min_long_double)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
}
END_TEST

START_TEST(exp_test) {
  if (s21_exp(my_inf) == exp(my_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_exp(my_min_inf) == exp(my_min_inf)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  ck_assert_int_eq(s21_exp(my_nan), exp(my_nan));
  ck_assert_int_eq(s21_exp(min_nan), exp(min_nan));
  ck_assert_int_eq(s21_exp(zero), exp(zero));
  ck_assert_int_eq(s21_exp(min_zero), exp(min_zero));
  x = s21_exp(small_num);
  y = exp(small_num);
  if (x == y) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  x = s21_exp(min_small_num);
  y = exp(min_small_num);
  if (x == y) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;

  x = s21_exp(big_num);
  y = exp(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(min_big_num);
  y = exp(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(zf);
  y = exp(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(mzf);
  y = exp(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(tf);
  y = exp(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(mtf);
  y = exp(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(big_float);
  y = exp(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(min_big_float);
  y = exp(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(small);
  y = exp(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(min_small);
  y = exp(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(long_double);
  y = exp(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_exp(min_long_double);
  y = exp(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(pow_test) {
  if (s21_pow(my_inf, 2) == pow(my_inf, 2)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  if (s21_pow(my_min_inf, 2) == pow(my_min_inf, 2)) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  x = s21_pow(my_nan, 2);
  y = pow(my_nan, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_nan, 2);
  y = pow(min_nan, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(zero, 2);
  y = pow(zero, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_zero, 2);
  y = pow(min_zero, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(small_num, 2);
  y = pow(small_num, 2);
  if (x == y) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  x = s21_pow(min_small_num, 2);
  y = pow(min_small_num, 2);
  if (x == y) flag = 1;
  ck_assert_int_eq(flag, 1);
  flag = 0;
  x = s21_pow(num, 2);
  y = pow(num, 2);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_num, 2);
  y = pow(min_num, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(8222.3, 2.1);
  y = pow(8222.3, 2.1);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_big_num, 2);
  y = pow(min_big_num, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(zf, 2);
  y = pow(zf, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(mzf, 2);
  y = pow(mzf, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(tf, 2);
  y = pow(tf, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(mtf, 2);
  y = pow(mtf, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(big_float, 2);
  y = pow(big_float, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_big_float, 2);
  y = pow(min_big_float, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(small, 2);
  y = pow(small, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_small, 2);
  y = pow(min_small, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(long_double, 2);
  y = pow(long_double, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_pow(min_long_double, 2);
  y = pow(min_long_double, 2);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sqrt_test) {
  x = s21_sqrt(my_inf);
  y = sqrt(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(my_min_inf);
  y = sqrt(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(s21_sqrt(my_nan), sqrt(my_nan));
  ck_assert_int_eq(s21_sqrt(min_nan), sqrt(min_nan));
  ck_assert_int_eq(s21_sqrt(zero), sqrt(zero));
  ck_assert_int_eq(s21_sqrt(min_zero), sqrt(min_zero));
  x = s21_sqrt(small_num);
  y = sqrt(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(min_small_num);
  y = sqrt(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(num);
  y = sqrt(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(min_num);
  y = sqrt(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(big_num);
  y = sqrt(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(min_big_num);
  y = sqrt(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(zf);
  y = sqrt(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(mzf);
  y = sqrt(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(tf);
  y = sqrt(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(mtf);
  y = sqrt(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(big_float);
  y = sqrt(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(min_big_float);
  y = sqrt(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(small);
  y = sqrt(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(min_small);
  y = sqrt(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(long_double);
  y = sqrt(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sqrt(min_long_double);
  y = sqrt(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(fmod_test) {
  x = s21_fmod(my_inf, 3);
  y = fmod(my_inf, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(my_min_inf, 3);
  y = fmod(my_min_inf, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(my_nan, 3);
  y = fmod(my_nan, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_nan, 3);
  y = fmod(min_nan, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(zero, 3);
  y = fmod(zero, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_zero, 3);
  y = fmod(min_zero, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(small_num, 3);
  y = fmod(small_num, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_small_num, 3);
  y = fmod(min_small_num, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(num, 3);
  y = fmod(num, 3);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_num, 3);
  y = fmod(min_num, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(big_num, 3);
  y = fmod(big_num, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(-22222.3, 3);
  y = fmod(-22222.3, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(zf, 3);
  y = fmod(zf, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(mzf, 3);
  y = fmod(mzf, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(tf, 3);
  y = fmod(tf, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(mtf, 3);
  y = fmod(mtf, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(big_float, 3);
  y = fmod(big_float, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_big_float, 3);
  y = fmod(min_big_float, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(small, 3);
  y = fmod(small, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_small, 3);
  y = fmod(min_small, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(long_double, 3);
  y = fmod(long_double, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_long_double, 3);
  y = fmod(min_long_double, 3);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);

  x = s21_fmod(my_inf, 2.5);
  y = fmod(my_inf, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(my_min_inf, 2.5);
  y = fmod(my_min_inf, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(my_nan, 2.5);
  y = fmod(my_nan, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_nan, 2.5);
  y = fmod(min_nan, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(zero, 2.5);
  y = fmod(zero, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_zero, 2.5);
  y = fmod(min_zero, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(small_num, 2.5);
  y = fmod(small_num, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_small_num, 2.5);
  y = fmod(min_small_num, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(num, 2.5);
  y = fmod(num, 2.5);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(num, 2.5);
  y = fmod(num, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(big_num, 2.5);
  y = fmod(big_num, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_big_num, 2.5);
  y = fmod(min_big_num, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(zf, 2.5);
  y = fmod(zf, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(mzf, 2.5);
  y = fmod(mzf, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(tf, 2.5);
  y = fmod(tf, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(0.5, 2.5);
  y = fmod(0.5, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(big_float, 2.5);
  y = fmod(big_float, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_big_float, 2.5);
  y = fmod(min_big_float, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(small, 2.5);
  y = fmod(small, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_small, 2.5);
  y = fmod(min_small, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(long_double, 2.5);
  y = fmod(long_double, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_fmod(min_long_double, 2.5);
  y = fmod(min_long_double, 2.5);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(log_test) {
  x = s21_log(my_inf);
  y = log(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(my_min_inf);
  y = log(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(my_nan);
  y = log(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_nan);
  y = log(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(zero);
  y = log(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_zero);
  y = log(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(small_num);
  y = log(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_small_num);
  y = log(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(num);
  y = log(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_num);
  y = log(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(big_num);
  y = log(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_big_num);
  y = log(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(zf);
  y = log(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(mzf);
  y = log(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(tf);
  y = log(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(mtf);
  y = log(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(big_float);
  y = log(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_big_float);
  y = log(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(small);
  y = log(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_small);
  y = log(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(long_double);
  y = log(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_log(min_long_double);
  y = log(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(sin_test) {
  x = s21_sin(my_inf);
  y = sin(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(my_min_inf);
  y = sin(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(my_nan);
  y = sin(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_nan);
  y = sin(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(zero);
  y = sin(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_zero);
  y = sin(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(small_num);
  y = sin(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_small_num);
  y = sin(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(num);
  y = sin(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_num);
  y = sin(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(big_num);
  y = sin(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_big_num);
  y = sin(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(zf);
  y = sin(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(mzf);
  y = sin(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(tf);
  y = sin(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(mtf);
  y = sin(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(big_float);
  y = sin(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_big_float);
  y = sin(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(small);
  y = sin(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_small);
  y = sin(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(long_double);
  y = sin(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_sin(min_long_double);
  y = sin(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(cos_test) {
  x = s21_cos(my_inf);
  y = cos(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(my_min_inf);
  y = cos(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(my_nan);
  y = cos(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_nan);
  y = cos(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(zero);
  y = cos(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_zero);
  y = cos(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(small_num);
  y = cos(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_small_num);
  y = cos(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(num);
  y = cos(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_num);
  y = cos(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(zf);
  y = cos(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(mzf);
  y = cos(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(tf);
  y = cos(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(mtf);
  y = cos(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(big_float);
  y = cos(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_big_float);
  y = cos(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(small);
  y = cos(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_small);
  y = cos(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(long_double);
  y = cos(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_cos(min_long_double);
  y = cos(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(tan_test) {
  x = s21_tan(my_inf);
  y = tan(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(my_min_inf);
  y = tan(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(my_nan);
  y = tan(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_nan);
  y = tan(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(zero);
  y = tan(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_zero);
  y = tan(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(small_num);
  y = tan(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_small_num);
  y = tan(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(num);
  y = tan(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_num);
  y = tan(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(zf);
  y = tan(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(mzf);
  y = tan(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(tf);
  y = tan(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(mtf);
  y = tan(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(big_float);
  y = tan(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_big_float);
  y = tan(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(small);
  y = tan(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_small);
  y = tan(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(long_double);
  y = tan(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_tan(min_long_double);
  y = tan(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(asin_test) {
  x = s21_asin(my_inf);
  y = asin(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(my_min_inf);
  y = asin(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(my_nan);
  y = asin(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_nan);
  y = asin(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(zero);
  y = asin(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_zero);
  y = asin(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(small_num);
  y = asin(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_small_num);
  y = asin(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(num);
  y = asin(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_num);
  y = asin(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(big_num);
  y = asin(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_big_num);
  y = asin(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(zf);
  y = asin(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(mzf);
  y = asin(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(tf);
  y = asin(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(mtf);
  y = asin(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(big_float);
  y = asin(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_big_float);
  y = asin(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(small);
  y = asin(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_small);
  y = asin(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(long_double);
  y = asin(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_asin(min_long_double);
  y = asin(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(atan_test) {
  x = s21_atan(my_inf);
  y = atan(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(my_min_inf);
  y = atan(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(my_nan);
  y = atan(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_nan);
  y = atan(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(zero);
  y = atan(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_zero);
  y = atan(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(small_num);
  y = atan(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_small_num);
  y = atan(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(num);
  y = atan(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_num);
  y = atan(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(big_num);
  y = atan(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_big_num);
  y = atan(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(zf);
  y = atan(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(mzf);
  y = atan(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(tf);
  y = atan(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(mtf);
  y = atan(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(big_float);
  y = atan(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_big_float);
  y = atan(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(small);
  y = atan(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_small);
  y = atan(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(long_double);
  y = atan(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_atan(min_long_double);
  y = atan(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(acos_test) {
  x = s21_acos(my_inf);
  y = acos(my_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(my_min_inf);
  y = acos(my_min_inf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(my_nan);
  y = acos(my_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_nan);
  y = acos(min_nan);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(zero);
  y = acos(zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_zero);
  y = acos(min_zero);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(small_num);
  y = acos(small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_small_num);
  y = acos(min_small_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(num);
  y = acos(num);
  snprintf(str1, sizeof(str1), "%16.6lf", x);
  snprintf(str2, sizeof(str1), "%16.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_num);
  y = acos(min_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(big_num);
  y = acos(big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_big_num);
  y = acos(min_big_num);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(zf);
  y = acos(zf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(mzf);
  y = acos(mzf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(tf);
  y = acos(tf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(mtf);
  y = acos(mtf);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(big_float);
  y = acos(big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_big_float);
  y = acos(min_big_float);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(small);
  y = acos(small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_small);
  y = acos(min_small);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(long_double);
  y = acos(long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
  x = s21_acos(min_long_double);
  y = acos(min_long_double);
  snprintf(str1, sizeof(str1), "%.6lf", x);
  snprintf(str2, sizeof(str1), "%.6lf", y);
  ck_assert_str_eq(str1, str2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, abs_test);
  tcase_add_test(tc1_1, fabs_test);
  tcase_add_test(tc1_1, floor_test);
  tcase_add_test(tc1_1, ceil_test);
  tcase_add_test(tc1_1, exp_test);
  tcase_add_test(tc1_1, pow_test);
  tcase_add_test(tc1_1, sqrt_test);
  tcase_add_test(tc1_1, fmod_test);
  tcase_add_test(tc1_1, log_test);
  tcase_add_test(tc1_1, sin_test);
  tcase_add_test(tc1_1, cos_test);
  tcase_add_test(tc1_1, tan_test);
  tcase_add_test(tc1_1, asin_test);
  tcase_add_test(tc1_1, atan_test);
  tcase_add_test(tc1_1, acos_test);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
